### ISSUE TITLE
Replace subprocess with another library

### ISSUE THREAD

**Issue by fx-biocoder** [fx-biocoder/Conservacion-de-codones-raros#5]

**Comment by andreeagspiridon** [comment]
Hello,
I would like to contribute to this.

**Comment by fx-biocoder** [comment]
> Hello, I would like to contribute to this.

Hello. Thanks for your interest in contributing to this project. You will see that [bioseeker.py](https://github.com/SouthernBio/BioSeeker/blob/main/bioseeker.py) uses `subprocess` to execute terminal commands, it would be great if you could find another way to execute these commands without that library, as I've been told it is unsafe. 

I have sent you an invitation to join the organization as a collaborator. After you accept it, you should be able to create a new branch and make the changes you see fit.

**Comment by fx-biocoder** [comment]
Hello again, I have deleted you by accident. I'm fairly new to Github Organizations so I'm still getting used to the control panel. I have sent you a new invitation.
